/*
# [Initial Schema Setup]
This script sets up the entire database schema for the SURYASAKSHI FPC application. It creates all necessary tables, defines relationships, establishes security policies (RLS), and sets up a trigger for automatic user profile creation.

## Query Description: This script is foundational and should be run on a new, empty Supabase project. It will create the following tables:
- `profiles`: Stores user data linked to the authentication system.
- `silage_sales`, `maize_purchases`, `other_expenses`, `soybean_purchases`, `soybean_sales`, `general_purchases`: These tables will hold the core business data, replacing the previous mock data.
- `activities`: This table will log all user actions for the "Recent Activity" feed.
This operation is safe to run on a new project but would be destructive if tables with the same names already exist.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "High"
- Requires-Backup: false (as it's for initial setup)
- Reversible: false (requires manual dropping of tables)

## Structure Details:
- **Tables Created**: `profiles`, `silage_sales`, `maize_purchases`, `other_expenses`, `soybean_purchases`, `soybean_sales`, `general_purchases`, `activities`
- **Primary Keys**: `id` (auto-incrementing bigint) for all tables.
- **Foreign Keys**: Links data tables to `profiles` table via `user_id`.

## Security Implications:
- RLS Status: Enabled on all new tables.
- Policy Changes: Yes, new policies are created to allow authenticated users to access and modify data.
- Auth Requirements: All data access requires an authenticated user session.

## Performance Impact:
- Indexes: Primary keys and foreign keys are automatically indexed.
- Triggers: One trigger is added to `auth.users` to create user profiles automatically.
- Estimated Impact: Low, as this is an initial setup on an empty database.
*/

-- 1. PROFILES TABLE
-- Stores public user data.
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE,
  updated_at timestamptz
);

-- RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to create a profile for new users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. SILAGE SALES TABLE
CREATE TABLE public.silage_sales (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    name_of_buyer text,
    mob_no text,
    date_of_perchase date,
    product text default 'SILAGE',
    weight_kg numeric,
    rate numeric,
    total_amount numeric,
    payment_status text,
    paid_amount numeric,
    invoice_no integer,
    address text
);
ALTER TABLE public.silage_sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage silage sales" ON public.silage_sales FOR ALL USING (auth.role() = 'authenticated');


-- 3. MAIZE PURCHASES TABLE
CREATE TABLE public.maize_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    name_of_farmer text,
    date_of_purchase date,
    address text,
    product text default 'MAIZE',
    weight_kg numeric,
    rate_maize numeric,
    total_amount numeric,
    payment_status text
);
ALTER TABLE public.maize_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage maize purchases" ON public.maize_purchases FOR ALL USING (auth.role() = 'authenticated');


-- 4. OTHER EXPENSES TABLE
CREATE TABLE public.other_expenses (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    expense_name text,
    date_of_expenses date,
    amount numeric
);
ALTER TABLE public.other_expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage other expenses" ON public.other_expenses FOR ALL USING (auth.role() = 'authenticated');


-- 5. SOYBEAN PURCHASES TABLE
CREATE TABLE public.soybean_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    name_0f_saler text,
    date_of_purchase date,
    product text default 'SOYABIN',
    weight_quintal numeric,
    rate numeric,
    total_price numeric,
    payment_status text
);
ALTER TABLE public.soybean_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage soybean purchases" ON public.soybean_purchases FOR ALL USING (auth.role() = 'authenticated');


-- 6. SOYBEAN SALES TABLE
CREATE TABLE public.soybean_sales (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    invoice_no integer,
    name_0f_buyer text,
    date_of_sale date,
    product text default 'SOYABIN SEED',
    quantity integer,
    rate numeric,
    total_price numeric,
    payment_status text
);
ALTER TABLE public.soybean_sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage soybean sales" ON public.soybean_sales FOR ALL USING (auth.role() = 'authenticated');


-- 7. GENERAL PURCHASES TABLE
CREATE TABLE public.general_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    name_of_seller text,
    mo_no text,
    purchase_date date,
    product text,
    amount numeric
);
ALTER TABLE public.general_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage general purchases" ON public.general_purchases FOR ALL USING (auth.role() = 'authenticated');


-- 8. ACTIVITIES TABLE
CREATE TABLE public.activities (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles,
    created_at timestamptz default now(),
    action text,
    target text
);
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can manage activities" ON public.activities FOR ALL USING (auth.role() = 'authenticated');

-- Add username to activities view by joining with profiles
CREATE OR REPLACE VIEW public.activities_with_username AS
SELECT 
    a.id,
    a.created_at,
    a.action,
    a.target,
    p.username
FROM public.activities a
JOIN public.profiles p ON a.user_id = p.id;
