/*
# [Operation Name]
Create General Purchases Table

## Query Description: 
This operation creates a new table named 'purchases' to store records of general-purpose purchases. This is essential for the 'General Purchases' feature in the application. It is a non-destructive operation that adds new structure without affecting existing data.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true

## Structure Details:
- Table(s) added: [public.purchases]
- Column(s) added: [id, created_at, name_of_seller, mo_no, purchase_date, product, amount]

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes
- Auth Requirements: Policies are added to ensure only authenticated users can manage records in this table.

## Performance Impact:
- Indexes: [Primary key index on 'id']
- Triggers: [None]
- Estimated Impact: [Low. Standard table creation.]
*/

-- Create the purchases table
CREATE TABLE public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name_of_seller TEXT NOT NULL,
    mo_no TEXT,
    purchase_date TIMESTAMPTZ NOT NULL,
    product TEXT NOT NULL,
    amount NUMERIC NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE public.purchases IS 'Stores records of general purchases for various products and supplies.';
COMMENT ON COLUMN public.purchases.name_of_seller IS 'Name of the person or company from whom the product was purchased.';
COMMENT ON COLUMN public.purchases.mo_no IS 'Mobile number of the seller.';
COMMENT ON COLUMN public.purchases.purchase_date IS 'Date of the purchase transaction.';
COMMENT ON COLUMN public.purchases.product IS 'Name or description of the product purchased.';
COMMENT ON COLUMN public.purchases.amount IS 'Total amount paid for the purchase.';

-- Enable Row Level Security
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- 1. Allow authenticated users to view all purchases
CREATE POLICY "Allow authenticated read access to purchases"
ON public.purchases
FOR SELECT
TO authenticated
USING (true);

-- 2. Allow authenticated users to insert purchases
CREATE POLICY "Allow authenticated insert access to purchases"
ON public.purchases
FOR INSERT
TO authenticated
WITH CHECK (true);

-- 3. Allow authenticated users to update purchases
CREATE POLICY "Allow authenticated update access to purchases"
ON public.purchases
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Allow authenticated users to delete purchases
CREATE POLICY "Allow authenticated delete access to purchases"
ON public.purchases
FOR DELETE
TO authenticated
USING (true);
